package scheduler

import (
	"bytes"
	"errors"
	"fmt"
	"path"
	"regexp"
	"strconv"
	"strings"
	"text/template"
	"time"

	"github.com/croutoncreations/sb-heartbeat/internal/config"
)

const checkoutCommit = "3d3c42e5aac5ba805825da76410c181273ba90b1"

var releaseVersionPattern = regexp.MustCompile(`^v[0-9]+\.[0-9]+\.[0-9]+$`)
var configPathPattern = regexp.MustCompile(`^[A-Za-z0-9._/-]+$`)

type workflowData struct {
	Cron           string
	Version        string
	ConfigPath     string
	TimeoutMinutes int
	Projects       []config.Project
}

func GitHub(cfg config.Config, version, configPath string) ([]byte, error) {
	if err := cfg.Validate(); err != nil {
		return nil, err
	}
	if !releaseVersionPattern.MatchString(version) {
		return nil, errors.New("SB Heartbeat version must be an exact release tag such as v0.1.0")
	}
	if configPath == "" || path.IsAbs(configPath) || path.Clean(configPath) != configPath ||
		!configPathPattern.MatchString(configPath) || configPath[0] == '-' || configPath == "." ||
		configPath == ".." || strings.HasPrefix(configPath, "../") {
		return nil, errors.New("workflow config path must be a clean, relative repository path")
	}
	tmpl, err := template.New("github").Funcs(template.FuncMap{
		"quote": strconv.Quote,
	}).Parse(githubWorkflowTemplate)
	if err != nil {
		return nil, fmt.Errorf("parse GitHub workflow template: %w", err)
	}
	var buffer bytes.Buffer
	data := workflowData{
		Cron: cfg.Scheduler.Cron, Version: version, ConfigPath: configPath,
		TimeoutMinutes: workflowTimeoutMinutes(cfg), Projects: cfg.Projects,
	}
	if err := tmpl.Execute(&buffer, data); err != nil {
		return nil, fmt.Errorf("render GitHub workflow: %w", err)
	}
	return buffer.Bytes(), nil
}

func workflowTimeoutMinutes(cfg config.Config) int {
	backoff := time.Duration(0)
	for retry := 0; retry < cfg.Defaults.Retries; retry++ {
		delay := cfg.Defaults.RetryBackoff * time.Duration(1<<retry)
		backoff += min(delay, 30*time.Second)
	}
	perBatch := cfg.Defaults.Timeout*time.Duration(cfg.Defaults.Retries+1) + backoff
	batches := (len(cfg.Projects) + cfg.Defaults.Concurrency - 1) / cfg.Defaults.Concurrency
	minutes := int((perBatch*time.Duration(batches)+time.Minute-1)/time.Minute) + 2
	return max(5, min(minutes, 360))
}

const githubWorkflowTemplate = `# Generated by SB Heartbeat. Re-run "sb-heartbeat install github" to replace it.
# Scheduled cron expressions use UTC and run the latest commit on the default branch.
# GitHub scheduled workflows may be delayed or dropped, and schedules in inactive public repositories may be disabled; workflow_dispatch remains available.
# Store project URLs as repository variables and low-privilege client keys as repository secrets by default; storage policy remains the repository owner's choice.
name: SB Heartbeat

on:
  schedule:
    - cron: {{ quote .Cron }}
  workflow_dispatch:

permissions:
  contents: read

jobs:
  heartbeat:
    runs-on: ubuntu-latest
    timeout-minutes: {{ .TimeoutMinutes }}
    env:
      SB_HEARTBEAT_VERSION: {{ .Version }}
    steps:
      - name: Check out configuration
        uses: actions/checkout@` + checkoutCommit + ` # v7.0.1

      - name: Install pinned SB Heartbeat release
        shell: bash
        run: |
          set -euo pipefail
          version="${SB_HEARTBEAT_VERSION#v}"
          archive="sb-heartbeat_${version}_linux_amd64.tar.gz"
          release="https://github.com/croutoncreations/sb-heartbeat/releases/download/${SB_HEARTBEAT_VERSION}"
          curl --fail --silent --show-error --location --output "${RUNNER_TEMP}/${archive}" "${release}/${archive}"
          curl --fail --silent --show-error --location --output "${RUNNER_TEMP}/checksums.txt" "${release}/checksums.txt"
          grep "  ${archive}$" "${RUNNER_TEMP}/checksums.txt" > "${RUNNER_TEMP}/expected-checksum.txt"
          (cd "${RUNNER_TEMP}" && sha256sum --check --strict expected-checksum.txt)
          mkdir -p "${RUNNER_TEMP}/sb-heartbeat-bin"
          tar -xzf "${RUNNER_TEMP}/${archive}" -C "${RUNNER_TEMP}/sb-heartbeat-bin" sb-heartbeat
          echo "${RUNNER_TEMP}/sb-heartbeat-bin" >> "${GITHUB_PATH}"

      - name: Run heartbeats
        env:
{{- range .Projects }}
          {{ .URL.Env }}: ${{ "{{" }} vars.{{ .URL.Env }} {{ "}}" }}
          {{ .APIKey.Env }}: ${{ "{{" }} secrets.{{ .APIKey.Env }} {{ "}}" }}
{{- end }}
        shell: bash
        run: |
          set -o pipefail
          set +e
          sb-heartbeat --config {{ .ConfigPath }} run --output json | tee "${RUNNER_TEMP}/sb-heartbeat-result.json"
          status=${PIPESTATUS[0]}
          set -e
          {
            echo '## SB Heartbeat heartbeat results'
            echo '~~~json'
            cat "${RUNNER_TEMP}/sb-heartbeat-result.json"
            echo '~~~'
          } >> "${GITHUB_STEP_SUMMARY}"
          exit "${status}"
`
